# Docker Compose para Produção (EC2)
# Uso: docker-compose -f docker-compose.prod.yml up -d

version: '3.8'

services:
  # Traefik - Reverse Proxy & SSL
  traefik:
    image: traefik:v3.0
    container_name: promata-traefik
    restart: always
    command:
      # API e Dashboard
      - --api.dashboard=true
      - --api.insecure=false

      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Provider Docker (não Swarm)
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=promata_public

      # Let's Encrypt
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@promata.com.br}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory

      # Logs
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --accesslog=true

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard (proteger em produção)

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt

    networks:
      - promata_public

    labels:
      - traefik.enable=true

      # Redirect HTTP -> HTTPS global
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true

      # Security headers middleware
      - traefik.http.middlewares.security-headers.headers.sslredirect=true
      - traefik.http.middlewares.security-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.security-headers.headers.stsPreload=true
      - traefik.http.middlewares.security-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.security-headers.headers.frameDeny=true

  # Nginx - Proxy para S3 (Frontend)
  frontend-proxy:
    image: nginx:alpine
    container_name: promata-frontend-proxy
    restart: always

    volumes:
      - ./nginx-s3-proxy.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - promata_public

    labels:
      - traefik.enable=true
      - traefik.docker.network=promata_public

      # Router HTTPS
      - traefik.http.routers.frontend.rule=Host(`promata.com.br`) || Host(`www.promata.com.br`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
      - traefik.http.routers.frontend.middlewares=security-headers
      - traefik.http.services.frontend.loadbalancer.server.port=80

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Backend NestJS
  backend:
    image: ${DOCKER_REGISTRY:-docker.io}/${IMAGE_NAME:-norohim/pro-mata-backend}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-promata-backend}
    restart: always

    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-2h}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - UMAMI_URL=${UMAMI_URL:-}
      - UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID:-}

    networks:
      - promata_public
      - promata_internal

    labels:
      - traefik.enable=true
      - traefik.docker.network=promata_public

      # Router HTTPS
      - traefik.http.routers.backend.rule=Host(`api.promata.com.br`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.routers.backend.middlewares=security-headers
      - traefik.http.services.backend.loadbalancer.server.port=3000

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: promata-database
    restart: always

    environment:
      - POSTGRES_DB=${POSTGRES_DB:-promata}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - promata_internal

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  traefik_letsencrypt:
    name: promata-traefik-letsencrypt
  postgres_data:
    name: promata-postgres-data

networks:
  promata_public:
    name: promata_public
    driver: bridge
  promata_internal:
    name: promata_internal
    driver: bridge
